use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "lowercase")]
#[allow(dead_code)]
pub enum Model {
    Gpt53Codex,
    Gpt5,
    Gpt5Mini,
    Gpt5Nano,
    Gpt4o,
    Gpt4oMini,
    Gpt4Turbo,
    Gpt4,
    Gpt35Turbo,
    DallE2,
    DallE3,
    Tts1,
    Tts1Hd,
    Whisper1,
    WhisperV2Large,
    TextEmbedding3Large,
    TextEmbedding3Small,
    TextEmbeddingAda002,
    OmniModerationLatest,
    TextModerationLatest,
    TextModerationStable,
    TextModeration007,
    O1Preview,
    O1Mini,
    O3Mini,
    O1,
    Gpt4oRealtimePreview,
    Gpt4o20240806,
    Gpt4o20240513,
    Gpt4oMini20240718,
    Gpt4Turbo20240409,
    Gpt4TurboPreview,
    Gpt4Preview,
    Gpt4_0613,
    Gpt4_0314,
    Gpt35Turbo0125,
    Gpt35Turbo1106,
    Gpt35TurboInstruct,
    Babbage002,
    Davinci002,
}

impl std::fmt::Display for Model {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Model::Gpt53Codex => "gpt-5.3-codex",
            Model::Gpt5 => "gpt-5.2",
            Model::Gpt5Mini => "gpt-5-mini",
            Model::Gpt5Nano => "gpt-5-nano",
            Model::Gpt4o => "gpt-4o",
            Model::Gpt4oMini => "gpt-4o-mini",
            Model::Gpt4Turbo => "gpt-4-turbo",
            Model::Gpt4 => "gpt-4",
            Model::Gpt35Turbo => "gpt-3.5-turbo",
            Model::DallE2 => "dall-e-2",
            Model::DallE3 => "dall-e-3",
            Model::Tts1 => "tts-1",
            Model::Tts1Hd => "tts-1-hd",
            Model::Whisper1 => "whisper-1",
            Model::WhisperV2Large => "whisper-v2-large",
            Model::TextEmbedding3Large => "text-embedding-3-large",
            Model::TextEmbedding3Small => "text-embedding-3-small",
            Model::TextEmbeddingAda002 => "text-embedding-ada-002",
            Model::OmniModerationLatest => "omni-moderation-latest",
            Model::TextModerationLatest => "text-moderation-latest",
            Model::TextModerationStable => "text-moderation-stable",
            Model::TextModeration007 => "text-moderation-007",
            Model::O1Preview => "o1-preview",
            Model::O1Mini => "o1-mini",
            Model::O1 => "o1",
            Model::O3Mini => "o3-mini",
            Model::Gpt4oRealtimePreview => "gpt-4o-realtime-preview",
            Model::Gpt4o20240806 => "gpt-4o-2024-08-06",
            Model::Gpt4o20240513 => "gpt-4o-2024-05-13",
            Model::Gpt4oMini20240718 => "gpt-4o-mini-2024-07-18",
            Model::Gpt4Turbo20240409 => "gpt-4-turbo-2024-04-09",
            Model::Gpt4TurboPreview => "gpt-4-turbo-preview",
            Model::Gpt4Preview => "gpt-4-0125-preview",
            Model::Gpt4_0613 => "gpt-4-0613",
            Model::Gpt4_0314 => "gpt-4-0314",
            Model::Gpt35Turbo0125 => "gpt-3.5-turbo-0125",
            Model::Gpt35Turbo1106 => "gpt-3.5-turbo-1106",
            Model::Gpt35TurboInstruct => "gpt-3.5-turbo-instruct",
            Model::Babbage002 => "babbage-002",
            Model::Davinci002 => "davinci-002",
        };
        write!(f, "{}", s)
    }
}
